export const genres = [
    "Action",
    "Adventure",
    "Crime",
    "Drama",
    "Fantasy",
    "Horror",
    "Mystery",
    "Romance",
    "Science Fiction",
    "Thriller",
    "Western",
    "2D Animation",
    "3D Animation",
    "Anime",
    "Computer Animation",
    "Stop Motion",
    "Traditional Animation",
    "Comedy",
    "Black Comedy",
    "Dramedy",
    "Satire",
    "Screwball Comedy",
    "Action Crime",
    "Caper",
    "Courtroom Drama",
    "Crime Thriller",
    "Detective",
    "Gangster",
    "Heist",
    "Legal Drama",
    "Neo-Noir",
    "Noir",
    "Police Procedural",
    "Psychological Thriller",
    "Spy Thriller",
    "Coming-of-Age",
    "Docudrama",
    "Historical Drama",
    "Legal Drama",
    "Medical Drama",
    "Melodrama",
    "Military Drama",
    "Political Drama",
    "Psychological Drama",
    "Teen Drama",
    "Dark Fantasy",
    "Epic",
    "Fantasy Adventure",
    "High Fantasy",
    "Low Fantasy",
    "Magical Realism",
    "Sword and Sorcery",
    "Urban Fantasy",
    "Biographical Drama",
    "Historical Comedy",
    "Historical Drama",
    "Historical Fiction",
    "Period Piece",
    "War Film",
    "Western",
    "Body Horror",
    "Found Footage",
    "Gothic Horror",
    "Monster Movie",
    "Psychological Horror",
    "Slasher",
    "Supernatural Horror",
    "Teen Horror",
    "Comedy Musical",
    "Drama Musical",
    "Fantasy Musical",
    "Musical Comedy",
    "Musical Drama",
    "Musical Romance",
    "Rock Musical",
    "Detective",
    "Film Noir",
    "Psychological Thriller",
    "Whodunit",
    "Comedy Romance",
    "Drama Romance",
    "Fantasy Romance",
    "Historical Romance",
    "Romantic Comedy",
    "Romantic Drama",
    "Teen Romance",
    "Cyberpunk",
    "Dystopian",
    "Hard Science Fiction",
    "Post-Apocalyptic",
    "Science Fantasy",
    "Space Opera",
    "Time Travel",
    "Action Thriller",
    "Crime Thriller",
    "Psychological Thriller",
    "Techno-Thriller",
    "Action Western",
    "Comedy Western",
    "Modern Western",
    "Revisionist Western",
    "Spaghetti Western",
    "Western Drama",
    "Avant-Garde",
    "Experimental",
    "Religious",
    "Sports"
];