export const typesOptions = [
    { value: "web_series", title: "Web Series" },
    { value: "documentary", title: "Documentary" },
    { value: "short_film", title: "Short Film" },
    { value: "animation", title: "Animation" },
    { value: "tv_series", title: "TV Series" },
    { value: "film", title: "Film" },
];

export const statusOptions  = [
    { value: "public", title: "Public" },
    { value: "private", title: "Private" }
]


export const languagesOptions  = [
    { value: "english", title: "English" },
    { value: "spanish", title: "Spanish" },
    { value: "french", title: "French" },
    { value: "german", title: "German" },
    { value: "chinese", title: "Chinese" },
    { value: "japanese", title: "Japanese" },
    { value: "korean", title: "Korean" },
    { value: "arabic", title: "Arabic" },
    { value: "portuguese", title: "Portuguese" },
    { value: "russian", title: "Russian" },
    { value: "italian", title: "Italian" },
    { value: "hindi", title: "Hindi" },
    { value: "dutch", title: "Dutch" },
    { value: "swedish", title: "Swedish" },
    { value: "turkish", title: "Turkish" },
    { value: "polish", title: "Polish" },
    { value: "thai", title: "Thai" },
    { value: "greek", title: "Greek" },
    { value: "hebrew", title: "Hebrew" },
    { value: "indonesian", title: "Indonesian" },
    { value: "vietnamese", title: "Vietnamese" },
    { value: "czech", title: "Czech" },
    { value: "danish", title: "Danish" },
    { value: "finnish", title: "Finnish" },
    { value: "norwegian", title: "Norwegian" },
    { value: "romanian", title: "Romanian" },
    { value: "bulgarian", title: "Bulgarian" },
    { value: "malay", title: "Malay" },
    { value: "hungarian", title: "Hungarian" },
    { value: "serbian", title: "Serbian" },
    { value: "slovak", title: "Slovak" },
    { value: "slovenian", title: "Slovenian" },
    { value: "croatian", title: "Croatian" },
    { value: "latvian", title: "Latvian" },
    { value: "lithuanian", title: "Lithuanian" },
    { value: "estonian", title: "Estonian" },
    { value: "macedonian", title: "Macedonian" },
    { value: "albanian", title: "Albanian" },
    { value: "georgian", title: "Georgian" },
    { value: "azerbaijani", title: "Azerbaijani" },
    { value: "kazakh", title: "Kazakh" },
    { value: "kyrgyz", title: "Kyrgyz" },
    { value: "mongolian", title: "Mongolian" },
    { value: "maltese", title: "Maltese" },
    { value: "burmese", title: "Burmese" },
    { value: "sinhalese", title: "Sinhalese" },
    { value: "nepali", title: "Nepali" },
    { value: "amharic", title: "Amharic" },
    { value: "swahili", title: "Swahili" },
    { value: "bengali", title: "Bengali" },
    { value: "telugu", title: "Telugu" },
    { value: "marathi", title: "Marathi" },
    { value: "tamil", title: "Tamil" },
    { value: "urdu", title: "Urdu" },
    { value: "kannada", title: "Kannada" },
    { value: "oriya", title: "Oriya" },
    { value: "punjabi", title: "Punjabi" },
    { value: "malayalam", title: "Malayalam" },
    { value: "gujarati", title: "Gujarati" },
    { value: "assamese", title: "Assamese" },
    { value: "maithili", title: "Maithili" },
    { value: "konkani", title: "Konkani" },
    { value: "nepali", title: "Nepali" },
    { value: "kashmiri", title: "Kashmiri" },
    { value: "sanskrit", title: "Sanskrit" },
    { value: "sindhi", title: "Sindhi" },
    { value: "dogri", title: "Dogri" },
    { value: "khasi", title: "Khasi" },
    { value: "manipuri", title: "Manipuri" },
    { value: "mizo", title: "Mizo" },
    { value: "garo", title: "Garo" },
    { value: "kokborok", title: "Kokborok" },
    { value: "bhili", title: "Bhili" },
    { value: "gondi", title: "Gondi" },
    { value: "khasi", title: "Khasi" },
    { value: "tulu", title: "Tulu" },
];
